import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Sparkles } from "lucide-react";
import { useState } from "react";
import { aiApi } from "../../../api/endpoints";
import { Button } from "../../../components/ui/Button";
import { Card, CardBody, CardHeader } from "../../../components/ui/Card";
import { Spinner } from "../../../components/ui/Spinner";
import { useAuth } from "../../../hooks/useAuth";
import type { Project } from "../../../types";

function Section({ title, items }: { title: string; items: string[] }) {
  if (!items || items.length === 0) return null;
  return (
    <div>
      <h4 className="mb-1 text-sm font-semibold text-primary-700">{title}</h4>
      <ul className="list-disc space-y-1 pl-5 text-sm text-primary-600">
        {items.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
    </div>
  );
}

export function AIReportTab({ project }: { project: Project }) {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const isOfficer = user?.role === "OFFICER";
  const [generating, setGenerating] = useState(false);

  const reportQuery = useQuery({ queryKey: ["ai-report", project._id], queryFn: () => aiApi.get(project._id) });

  const generate = async () => {
    setGenerating(true);
    try {
      await aiApi.generate(project._id);
      queryClient.invalidateQueries({ queryKey: ["ai-report", project._id] });
    } finally {
      setGenerating(false);
    }
  };

  if (reportQuery.isLoading) return <Spinner label="Loading AI report..." />;
  const report = reportQuery.data;

  return (
    <div className="space-y-4">
      {isOfficer && (
        <Button onClick={generate} disabled={generating}>
          <Sparkles className="h-4 w-4" /> {generating ? "Generating..." : "Generate AI Investigation Summary"}
        </Button>
      )}

      {!report && <p className="text-sm text-primary-400">No AI report generated yet for this project.</p>}

      {report?.status === "UNAVAILABLE" && (
        <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-800">
          AI summary temporarily unavailable. Deterministic detection results above are unaffected — the officer can proceed with the
          rule/ML/CV findings directly.
        </div>
      )}

      {report?.status === "GENERATED" && (
        <Card>
          <CardHeader title="AI Investigation Summary" subtitle={`Generated by ${report.modelName} on ${new Date(report.generatedAt).toLocaleString()}`} />
          <CardBody className="space-y-4">
            <p className="rounded-lg bg-primary-50 p-3 text-sm text-primary-800">{report.executiveSummary}</p>
            <Section title="Key Findings" items={report.keyFindings} />
            <Section title="Financial Observations" items={report.financialObservations} />
            <Section title="Progress Observations" items={report.progressObservations} />
            <Section title="Evidence Observations" items={report.evidenceObservations} />
            <Section title="Possible Concerns" items={report.possibleConcerns} />
            <Section title="Recommended Actions" items={report.recommendedActions} />
            <Section title="Questions for Contractor" items={report.questionsForContractor} />
          </CardBody>
        </Card>
      )}
    </div>
  );
}
